config_type: "prediction" # options: data_preprocessor, prediction, evaluation

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  # Base input directory
  input_dir: "input/data/pdb-dbv5/protein_complex_graphs"

classification_settings:
  # defines the construction of training and testing dataset
  type: "gnn" # supported values: baseline, gnn
  pos_neg_ratio: .1
  n_iterations: 5
  n_epochs: 10
  weighted_loss: False
  models:
    - name: "gcn_ff"
      active: False

    - name: "gat_ff"
      active: False

    - name: "nnconv_ff"
      active: False

    - name: "egat_ff"
      active: True


output_settings:
  output_dir: "output/raw/20230426"
  prefix: "gnn2_ff2_pn0.1_weightedloss"   # default: none; default file name = <output_prefix>_<model_name>_output.csv
  # example: lr_n5_output.csv