config_type: "prediction" # options: data_preprocessor, prediction, evaluation

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  # Base input directory
  input_dir: "input/data/pdb-dbv5/residue_features_dataset"

  # Names of training and testing file(s) to be read and processed.
  # Ignored for gnn models
  file_names:
    train: [ "train.csv" ]
    test: [ "test.csv" ]

classification_settings:
  # defines the construction of training and testing dataset
  type: "baseline" # supported values: baseline, gnn
  n_iterations: 5
  train_proportion: 0.8
  label_col: "label"
  models:
    - name: "lr"
      active: True
      C: [0.01, 0.1, 1]

    - name: "rf"
      active: True
      n_estimators: [10, 50, 100]
      max_depth: [3, 5]


output_settings:
  output_dir: "output/raw/20230425"
  prefix: "pdb-dbv5"   # default: none; default file name = <output_prefix>_<model_name>_output.csv
  # example: lr_n5_output.csv